### ISSUE TITLE
Five problems, fixes and other concerns 

### ISSUE THREAD

**Issue by mmikailov** [cburgelab/RBNS_pipeline#4]
Could you please verify the below problem and its fix? 

**Problem 1: TypeError: __init__() takes at least 3 arguments (1 given)**
Traceback (most recent call last):
  File "/projects/mikem/applications/anaconda2/envs/rbns_pipeline/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/projects/mikem/applications/anaconda2/envs/rbns_pipeline/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/projects/mikem/applications/rbns_pipeline4/rbns_pipeline/src/RBNS_fold_split_reads.py", line 199, in get_Ppaired_DotBracket_andletters_for_reads_F_for_block
    threeP_adapter )
  File "/projects/mikem/applications/rbns_pipeline4/rbns_pipeline/src/RBNS_fold_split_reads.py", line 1288, in get_MFE_DotBracket_and_symbol_over_reads
    dotbracket_str = get_elementstring_from_DotBracket( dot_struc ).replace( "t", "f" )
  File "/projects/mikem/applications/rbns_pipeline4/rbns_pipeline/src/RBNS_fold_split_reads.py", line 1307, in get_elementstring_from_DotBracket
    bg = cgb.BulgeGraph()
TypeError: __init__() takes at least 3 arguments (1 given)

**Fixing Problem 1 in RBNS_fold_split_reads.py**
Comment out the below shown two lines (around 1305 and 1306): 
   bg = cgb.BulgeGraph()
    bg.from_dotbracket( DotBracket_str )

Add this line (around 1307): 
   bg = cgb.BulgeGraph.from_dotbracket(DotBracket_str)

**Comment by mmikailov** [comment]
Could you please verify the below problem and its fix?

**Problem 2: ZeroDivisionError: float division by zero**

Traceback (most recent call last):
  File "/projects/mikem/applications/rbns_pipeline4/rbns_pipeline/src/RBNS_main.py", line 3573, in <module>
    main()
  File "/projects/mikem/applications/rbns_pipeline4/rbns_pipeline/src/RBNS_main.py", line 3562, in main
    b = Bnse( settings, args.counts_on_cluster )
  File "/projects/mikem/applications/rbns_pipeline4/rbns_pipeline/src/RBNS_main.py", line 106, in __init__
    self.plot_Ppaired_over_top_enriched_kmers_and_flanking_and_RbyPpairedBin()
  File "/projects/mikem/applications/rbns_pipeline4/rbns_pipeline/src/RBNS_main.py", line 3005, in plot_Ppaired_over_top_enriched_kmers_and_flanking_and_RbyPpairedBin
    effective_R_D )
  File "/projects/mikem/applications/rbns_pipeline4/rbns_pipeline/src/RBNS_fold_split_reads.py", line 844, in plot_RBNS_Ppaired_ratio_w_sig
    Ppaired = Ppaired_D[idx]['Ppaired_sum'] / Ppaired_D[idx]['counts']
ZeroDivisionError: float division by zero

**Fixing Problem 2 in RBNS_fold_split_reads.py**
Before line "Ppaired = Ppaired_D[idx]['Ppaired_sum'] / Ppaired_D[idx]['counts']" insert the below shown lines to avoid the zero division error: 
               if 0 == Ppaired_D[idx]['counts']:        
                   continue

**Comment by mmikailov** [comment]
Could you please verify the below problem and its fix?

**Problem 3: IndexError: list index out of range**
Traceback (most recent call last):
  File "/projects/mikem/applications/rbns_pipeline4/rbns_pipeline/src/RBNS_main.py", line 3574, in <module>
    main()
  File "/projects/mikem/applications/rbns_pipeline4/rbns_pipeline/src/RBNS_main.py", line 3563, in main
    b = Bnse( settings, args.counts_on_cluster )
  File "/projects/mikem/applications/rbns_pipeline4/rbns_pipeline/src/RBNS_main.py", line 106, in __init__
    self.plot_Ppaired_over_top_enriched_kmers_and_flanking_and_RbyPpairedBin()
  File "/projects/mikem/applications/rbns_pipeline4/rbns_pipeline/src/RBNS_main.py", line 3006, in plot_Ppaired_over_top_enriched_kmers_and_flanking_and_RbyPpairedBin
    effective_R_D )
  File "/projects/mikem/applications/rbns_pipeline4/rbns_pipeline/src/RBNS_fold_split_reads.py", line 870, in plot_RBNS_Ppaired_ratio_w_sig
    skip_if_already_exists = False )
  File "/projects/mikem/applications/rbns_pipeline4/rbns_pipeline/src/RBNS_plots.py", line 1517, in plot_Ppaired_ratio_of_motif
    avg_fold_probs_by_motif_and_pos_D[lib_annot][motif_num][motif_pos]
IndexError: list index out of range

**Fixing Problem 3 in RBNS_plots.py**
Add the below two lines (around 1517, 1518) before line "conc_avg_prob =\": 
               if lib_annot >= len (avg_fold_probs_by_motif_and_pos_D):  
                   continue

**Comment by mmikailov** [comment]
Could you please verify the below problem and its fix?

**Problem 4: KeyError: 'input'**
Traceback (most recent call last):
  File "/projects/mikem/applications/rbns_pipeline4/rbns_pipeline/src/RBNS_main.py", line 3574, in <module>
    main()
  File "/projects/mikem/applications/rbns_pipeline4/rbns_pipeline/src/RBNS_main.py", line 3563, in main
    b = Bnse( settings, args.counts_on_cluster )
  File "/projects/mikem/applications/rbns_pipeline4/rbns_pipeline/src/RBNS_main.py", line 106, in __init__
    self.plot_Ppaired_over_top_enriched_kmers_and_flanking_and_RbyPpairedBin()
  File "/projects/mikem/applications/rbns_pipeline4/rbns_pipeline/src/RBNS_main.py", line 3006, in plot_Ppaired_over_top_enriched_kmers_and_flanking_and_RbyPpairedBin
    effective_R_D )
  File "/projects/mikem/applications/rbns_pipeline4/rbns_pipeline/src/RBNS_fold_split_reads.py", line 870, in plot_RBNS_Ppaired_ratio_w_sig
    skip_if_already_exists = False )
  File "/projects/mikem/applications/rbns_pipeline4/rbns_pipeline/src/RBNS_plots.py", line 1814, in plot_Ppaired_ratio_of_motif
    Ppaired = abs_Ppaireds_by_motifpos_annot_D[pos][lib_annot]
KeyError: 'input'

**Fixing Problem 4 in RBNS_plots.py**
Add the below two lines before line "Ppaired = abs_Ppaireds_by_motifpos_annot_D[pos][lib_annot]": 
               if lib_annot not in abs_Ppaireds_by_motifpos_annot_D[pos]: 
                   continue

**Comment by mmikailov** [comment]
Could you please verify the below problem and its fix?

**Problem 5: TypeError: get_suboptimal_block_sampled_DotBracket_reads_F() takes at least 5 arguments (4 given)**
Traceback (most recent call last):
  File "/projects/mikem/miniconda/miniconda2/envs/rbns_pipeline/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
Process Process-4:
Traceback (most recent call last):
  File "/projects/mikem/miniconda/miniconda2/envs/rbns_pipeline/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
    self.run()
  File "/projects/mikem/miniconda/miniconda2/envs/rbns_pipeline/lib/python2.7/multiprocessing/process.py", line 114, in run
  File "/projects/mikem/miniconda/miniconda2/envs/rbns_pipeline/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
TypeError: get_suboptimal_block_sampled_DotBracket_reads_F() takes at least 5 arguments (4 given)
TypeError: get_suboptimal_block_sampled_DotBracket_reads_F() takes at least 5 arguments (4 given)

**Fixing Problem 5 in RBNS_main.py**
Added 5th parameter (num_reads_per_block) in this call in RBNS_main.py (about line 2887): 
                   p = multiprocessing.Process(
                           target = RBNS_fold_split_reads.get_suboptimal_block_sampled_DotBracket_reads_F,
                           args = (
                               gz_F,
                               self.settings.get_property('temp'),
                               self.settings.get_property('scratch_dir'),
                               block_idx
                               , num_reads_per_block 
                               ) )

**Comment by mmikailov** [comment]
Could you please advise on the below concerns - how to fix them?

### Other concerns in the source codes
**shell-init: error ...**
EXECUTING fold_each_reads_by_block_F() in RBNS_main.py


	2,891 reads in 20 nM
	2,907 reads in Input
**shell-init: error** retrieving current directory: getcwd: cannot access parent directories: No such file or directory
copying to /projects/mikem/applications/rbns_pipeline5/runs/run_8306812/scratch/RBFOX3_input.block_0_34146/RBFOX3_input.reads
	DONE copying RBFOX3_input.reads
FINISHED SUCCESSFULLY! Copied 2,897 reads to /projects/mikem/applications/rbns_pipeline5/runs/run_8306812/results/split_reads/fld/by_block/RBFOX3_input.block_0.w_struc.reads.gz at 2022_Dec_21__14h_44m_51s
	Took 43 sec.
**shell-init: error** retrieving current directory: getcwd: cannot access parent directories: No such file or directory
copying to /projects/mikem/applications/rbns_pipeline5/runs/run_8306812/scratch/RBFOX3_20.block_0_1726/RBFOX3_20.reads
	DONE copying RBFOX3_20.reads
FINISHED SUCCESSFULLY! Copied 2,876 reads to /projects/mikem/applications/rbns_pipeline5/runs/run_8306812/results/split_reads/fld/by_block/RBFOX3_20.block_0.w_struc.reads.gz at 2022_Dec_21__14h_44m_53s
	Took 44 sec.


FINISHED with fold_each_reads_by_block_F() in RBNS_main.py
**RuntimeWarning messages**
/projects/mikem/applications/rbns_pipeline5/RBNS_pipeline/src/RBNS_lib.py:444: RuntimeWarning: divide by zero encountered in divide
  return profile.get_libfracs() / input_profile.get_libfracs()
/projects/mikem/applications/rbns_pipeline5/RBNS_pipeline/src/RBNS_lib.py:444: RuntimeWarning: invalid value encountered in divide
  return profile.get_libfracs() / input_profile.get_libfracs()
/home/mikem/.local/lib/python2.7/site-packages/numpy/core/_methods.py:112: RuntimeWarning: invalid value encountered in subtract
  x = asanyarray(arr - arrmean)
/projects/mikem/applications/rbns_pipeline5/RBNS_pipeline/src/RBNS_utils.py:200: RuntimeWarning: invalid value encountered in double_scalars
  Zscore = ( val - mean ) / st_dev
/projects/mikem/applications/rbns_pipeline5/RBNS_pipeline/src/RBNS_main.py:1512: RuntimeWarning: invalid value encountered in double_scalars
  R = adapter_freq_this_lib / adapter_freq_effective_input_lib
/projects/mikem/applications/rbns_pipeline5/RBNS_pipeline/src/RBNS_main.py:1512: RuntimeWarning: divide by zero encountered in double_scalars
  R = adapter_freq_this_lib / adapter_freq_effective_input_lib
/projects/mikem/applications/rbns_pipeline5/RBNS_pipeline/src/RBNS_utils.py:283: RuntimeWarning: invalid value encountered in double_scalars
  ((4. ** k) + read_len - k - (R * (read_len - k + 1)))
